### ISSUE TITLE
unable to track items

### ISSUE THREAD

**Issue by PurdraDan** [Br00ty/DS3_AP_Maptracker#2]
I'm unable to track all these triangle items, is it broken or am I missing a setting? Only the square ones seem trackable?

example:
![image](https://github.com/Br00ty/DS3_AP_Maptracker/assets/85551381/87193160-5c1e-4a12-a93e-5d868aa09172)

**Comment by Br00ty** [comment]
@PurdraDan those triangles are just part of the map image, they are not actually a part of the tracker. only the green checks are as they are the important checks.

**Comment by PurdraDan** [comment]
So out of the 875 checks, those will never be progressive items and only common items or traps or something?
Kinda weird that they are then counted as Checks, if they are never gonna be progressive ones.
